# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: sshnaidm
name: cdktf_aws
version: 0.1.0
readme: README.md
authors:
  - Sagi Shnaidman (@sshnaidm)
description: "CDK Terraform for AWS"
license_file: LICENSE
# tags:
# # tags so people can search for collections https://galaxy.ansible.com/search
# # tags are all lower-case, no spaces, no dashes.
#   - example1
#   - example2
repository: https://github.com/sshnaidm/cdktf-collection
#documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/sshnaidm/cdktf-collection
issues: https://github.com/sshnaidm/cdktf-collection/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
